[workspace.package]
version = "0.1.0"
authors = ["Salman Abuhaimed <salman.f.abuhaimed@gmail.com>"]
edition = "2024"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[workspace]
resolver = "3"
members = [
    "web",
    "gui"
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.120"
indexmap = { version = "2.3.0", features = ["serde"] }
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
log = "0.4"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }
# egui = { git = "https://github.com/emilk/egui", branch = "master" }
# egui_extras = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# egui = { path = "../egui/crates/egui" }
# eframe = { path = "../egui/crates/eframe" }
