DO $$ BEGIN
    CREATE TYPE marriage_status AS ENUM ('married', 'separated');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS marriages
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    husband_id INT8 NOT NULL,
    wife_id INT8 NOT NULL,
    status marriage_status NOT NULL DEFAULT 'married',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

   CONSTRAINT fk_husband
      FOREIGN KEY(husband_id)
        REFERENCES members(id)
        ON DELETE CASCADE,
   CONSTRAINT fk_wife
      FOREIGN KEY(wife_id)
        REFERENCES members(id)
        ON DELETE CASCADE,
   CONSTRAINT chk_distinct_spouses CHECK (husband_id <> wife_id),
   CONSTRAINT uq_marriage UNIQUE (husband_id, wife_id)
);

CREATE INDEX IF NOT EXISTS idx_marriages_wife_id ON marriages(wife_id);
